config/routes.rb
Rails.application.routes.draw do
  get  "sessions/sign_up_form"
  post "sessions/sign_up"
  get  "sessions/sign_out"

  get  "sessions/sign_in_form"
  post "sessions/sign_in"

  resources :user
  resources :songs
  resources :albums
  resources :playlists

  root "home#index"
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string
#  file_cover :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Album < ApplicationRecord
  has_many :songs, dependent: :destroy
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Genre < ApplicationRecord
  has_and_belongs_to_many :songs
end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  id         :integer          not null, primary key
#  title      :string
#  file_cover :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Playlist < ApplicationRecord
  has_and_belongs_to_many :songs
  has_many :genres, through: :songs
  belongs_to :user
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id          :integer          not null, primary key
#  title       :string
#  artist      :string
#  duration    :integer
#  album_id    :integer
#  playlist_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  file        :string
#

class Song < ApplicationRecord
  mount_uploader :file, SongUploader

  has_and_belongs_to_many :genres, optional: true
  has_and_belongs_to_many :playlist
  belongs_to :album, optional: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string
#  nick_name  :string
#  role       :integer          default("user")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_many :playlists
  has_many :songs, through: :playlists

  enum role: %i[user artist admin]

  serialize :auth_meta_data
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    run Album::Index
    render cell(Album::Cell::Index, result["model"])
  end

  def new
    run Album::Create::Present
    render cell(Album::Cell::New, @form)
  end

  def create
    # binding.pry
    run Album::Create do |result|
      redirect_to albums_path
    end

    render cell(Album::Cell::New, @form)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def tyrant
    Tyrant::Session.new(request.env["warden"])
  end

  helper_method :tyrant
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def new
    # form Playlist::Create
  end

  def create
    # run Playlist::Create do |op|
    #   flash[:notice] = "Created playlist: [#{op.model.title}]"
    #
    #   # return redirect_to playlist_index_path(op.model)
    # end
    #
    # render action: :new
    result = Playlist::Create.(
             params,
             "current_user" => Warden.get_user)
  end

  private
    def params
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action only: %i[sign_in_form sign_in] do
    redirect_to root_path if tyrant.signed_in?
  end

  def sign_up_form
    run Session::SignUp::Present
    render cell(Session::Cell::SignUpForm, @form)
  end

  def sign_up
    run Session::SignUp, params[:user] do |_op|
      flash[:notice] = "Please log in now!"
      return redirect_to sessions_sign_in_form_path
    end
    render cell(Session::Cell::SignUpForm, @form)
  end

  def sign_in_form
    run Session::SignIn::Present
    render cell(Session::Cell::SignInForm, @form)
  end

  def sign_in
    run Session::SignIn, params[:session] do |op|
      tyrant.sign_in!(op["model"])
      return redirect_to root_path
    end

    render cell(Session::Cell::SignInForm, @form)
  end

  def sign_out
    run Session::SignOut do
      tyrant.sign_out!
      redirect_to root_path
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationRecord
  def index
    run Song::Index
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    form Song::Create
  end

  def create
    run Song::Create do |op|
      flash[:notice] = "Created song: [#{op.model.title}] \"#{op.model.artist}\""

      return redirect_to song_path(op.model)
    end

    render action: :new
  end

  def update
    run Song::Update
  end

  def delete
    run Song::Delete
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.slim
h2 Hello!!!
- if tyrant.current_user.artist?
    = link_to "Create album"
    = link_to "Create playlist"
- else
    = link_to "Create playlist", new_playlist_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'
      ul.nav.navbar-nav.navbar-right
        - if tyrant.signed_in?
          li
            = link_to "Hi, #{tyrant.current_user.nick_name}"
          li
            = link_to "Sign out", sessions_sign_out_path
        - else
          li
            = link_to "Sign in", sessions_sign_in_form_path
          li
            = link_to "Sign up", sessions_sign_up_form_path

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Ruby Rogues'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Ruby Rogues'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/playlists/new.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      h1 New playlist
      = simple_form_for(model, url: playlist_path, as: :playlist) do |f|
        .form-group
          = f.input :title, input_html: { class: 'form-control' }
          = f.fields_for :picture_attributes do |p|
            = p.file_field :file
        .form-group
          .btn-group role="group" aria-label="actions"
            = f.submit "Create", class: "btn btn-primary"
            = link_to 'Back', playlists_path, type: "button", class: "btn btn-success"